### ISSUE TITLE
juku emulaator

### ISSUE THREAD

**Issue by artizirk** [infoaed/juku3000#3]
siin emu.rar kaustas paistab olema juku emulaator, lehel all pool on ka üks ketta pilt
http://bashkiria-2m.narod.ru/index/files/0-11

**Comment by jeerum** [comment]
Kas leiduks peale selle kettapildi veel kasutatavaid :) 
Olid asjad :D

**Comment by boamaod** [comment]
See üks emulaator täitsa töötab, kuigi mitte kõigi teksti ja graafikarežiimidega. Lisasin [README](/infoaed/juku3000/blob/master/README.md)-sse lühikese emulaatorite kokkuvõtte ja hetkel tundub, et peaks ise mõne vabavaralise töökorda tegema. Selleks võib uue issue ka avada.

**Comment by boamaod** [comment]
Kuna otsingud jätkuvalt toovad siia, siis märgin ära, et alates 2025 veebruarist on JUKU tugi [MAME emulaatori ametlikus harus](https://j3k.infoaed.ee/mame-k%C3%A4ivitamine/) kõige täielikum, sj töötavad nii eri graafika- kui tekstirežiimid, hiir kui heligeneraator. Täiendusi [oleks veel vaja](https://github.com/infoaed/juku3000/issues?q=is%3Aissue%20state%3Aopen%20label%3Aemulaator), aga üldiselt kogu [praeguseks taastatud JUKU tarkvara](https://j3k.infoaed.ee/tarkvara-kataloog/) MAMEs ka töötab.
